# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=utils.get_file_path)),
                ('activity', models.CharField(choices=[('Football', 'Football'), ('Hockey', 'Hockey')], default='Football', max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('date_end', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('top_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
